#!/bin/bash

# Check out the tip of a git branch, and construct a simplified tarball that
# contains the necessary directories and files for the ceph, libceph, and rbd
# kernel modules. This tarball will be Source0 for the RPM.

# Some of this code is duplicated from the configure script. A future
# improvement would be to merge the two somehow.

set -e

# Git repo information.
git_clone=ceph-client
git_branch=rhel7

if [[ ! -d $git_clone ]]; then
  echo Please clone https://github.com/ceph/ceph-client to ${git_clone}.
  echo If building in Jenkins, you can use the Multi SCM plugin to do this.
  exit 1
fi

# Get version information
pushd $git_clone >/dev/null
  git checkout $git_branch
  # We hardcode this git_tag because RHEL 7 is all that we support.
  git_tag=v3.10.0
  git_short_commit=$(git rev-parse --short=7 HEAD)
popd >/dev/null

if [[ $git_tag != v* ]]; then
  echo $git_tag does not look like a normal kernel tag. Please verify.
  exit 1
fi

# Version number suitable for RPM:
rpm_version=$(echo $git_tag | sed -e s/^v// -e s/-rc[0-9]*$//)

# Directory name for the files inside our tarball:
tarball_dir=ceph-${rpm_version}-${git_short_commit}

# Tarball file:
tarball_file=${tarball_dir}.tar.xz

# Debugging:
echo RPM Version: ${rpm_version}
echo Git short commit: ${git_short_commit}
echo Tarball filename: ${tarball_file}
echo Directory inside tarball: ${tarball_dir}

if [[ -d ${tarball_dir} ]]; then
  echo ${tarball_dir} already exists. Please remove it.
  exit 1
fi

# Remove $TARBALL, if it exists, without asking.
[[ -f ${tarball_file} ]] && rm ${tarball_file}

mkdir ${tarball_dir}

# License file
cp ${git_clone}/COPYING ${tarball_dir}/COPYING

# Libceph
mkdir -p ${tarball_dir}/net
cp -r ${git_clone}/net/ceph ${tarball_dir}/net/

# Ceph
mkdir -p ${tarball_dir}/fs
cp -r ${git_clone}/fs/ceph ${tarball_dir}/fs/

# RBD
mkdir -p ${tarball_dir}/drivers/block
cp ${git_clone}/drivers/block/rbd.c       ${tarball_dir}/drivers/block/
cp ${git_clone}/drivers/block/rbd_types.h ${tarball_dir}/drivers/block/
cp ${git_clone}/drivers/block/Kconfig     ${tarball_dir}/drivers/block/
cp ${git_clone}/drivers/block/Makefile    ${tarball_dir}/drivers/block/
# The standard drivers/block/Makefile contains a lot of rules.
# Simplify the Makefile so that we're only building RBD.
sed -i '/rbd\.o/!d' ${tarball_dir}/drivers/block/Makefile

# Headers
mkdir -p ${tarball_dir}/include/linux
cp -r ${git_clone}/include/linux/ceph  ${tarball_dir}/include/linux/
cp -r ${git_clone}/include/linux/crush ${tarball_dir}/include/linux/

# Tar it up
tar -cJf ${tarball_file} ${tarball_dir}
rm -r ${tarball_dir}

echo "wrote ${tarball_file}"
