#!/bin/bash

# Check out the tip of a git branch, and construct a simplified tarball that
# only contains the fs/ceph directory. This will be Source0 for the RPM.

# Git repo
GIT_CLONE=ceph-client
GIT_BRANCH=wip-rhel7

if [[ ! -d $GIT_CLONE ]]; then
  echo Please clone https://github.com/ceph/ceph-client to ${GIT_CLONE}.
  echo If building in Jenkins, you can use the Multi SCM plugin to do this.
  exit 1
fi

# Get version information
pushd $GIT_CLONE >/dev/null
  git checkout $GIT_BRANCH
  GIT_TAG=$(git describe --abbrev=0 --tags HEAD)
  GIT_COMMIT=$(git rev-parse HEAD)
  GIT_SHORT_COMMIT=$(git rev-parse --short=7 HEAD)
popd >/dev/null

if [[ $GIT_TAG != v* ]]; then
  echo $GIT_TAG does not look like a normal kernel tag. Please verify.
  exit 1
fi

# Version number for RPM:
RPM_VERSION=$(echo $GIT_TAG | sed -e s/^v// -e s/-rc[0-9]*$//)

# Directory name for our tarball to RPM:
DIR=ceph-${RPM_VERSION}-${GIT_SHORT_COMMIT}
# Tarball file:
TARBALL=${DIR}.tar.xz

# Debugging:
echo Git tag: ${GIT_TAG}
echo Git commit: ${GIT_COMMIT}
echo Git shortcommit: ${GIT_SHORT_COMMIT}
echo Directory name: ${DIR}
echo Tarball name: ${TARBALL}

if [[ -d ${DIR} ]]; then
  echo ${DIR} already exists. Please remove it.
  exit 1
fi

# Remove $TARBALL, if it exists, without asking.
[[ -f ${TARBALL} ]] && rm ${TARBALL}

cp -r $GIT_CLONE/fs/ceph $DIR
tar -cJf ${TARBALL} $DIR
rm -r $DIR

echo "wrote ${TARBALL}"
